version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./edge_proxy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8080:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'edge_proxy' --service-node 'edge_proxy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_1_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service1/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8786:8786"
      - "8788:8788"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-1' --service-node 'service-1' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  service_1:
    build: service1/
    ports:
    - "5001:5001"

  service_2_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service2/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8789:8789"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-2' --service-node 'service-2' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  service_2:
    build: service2/
    ports:
    - "5002:5002"

  service_3_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service3/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8790:8790"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-3' --service-node 'service-3' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  service_3:
    build: service3/
    ports:
    - "5003:5003" 

  service_4_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service4/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8792:8792"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-4' --service-node 'service-4' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  service_4:
    build: service4/
    ports:
    - "5004:5004"

  service_5_envoy:
    image: envoyproxy/envoy-alpine:v1.7.0
    volumes:
      - ./service5/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "8793:8793"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --v2-config-only -l info --service-cluster 'service-5' --service-node 'service-5' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  

  service_5:
    build: service5/
    ports:
    - "5005:5005"
